using System;
using System.Collections.Generic;

namespace Riva.Models.RivaData
{
    public partial class RivaDataProducts
    {
        public int SerialId { get; set; }
        public string ProductNo { get; set; }
        public string ProductName { get; set; }
        public string Comments1 { get; set; }
        public bool? Discontinued { get; set; }
        public decimal? UnitPrice { get; set; }
        public string PriceScheme { get; set; }
        public string CellName { get; set; }
        public decimal? MinCost { get; set; }
        public decimal? AvgCost { get; set; }
        public decimal? MaxCost { get; set; }
        public string Sku { get; set; }
        public bool? SkuApproval { get; set; }
        public string SkucountryOrigin { get; set; }
        public double? GoldDwt { get; set; }
        public double? TempWeight { get; set; }
        public double? InitialWeight { get; set; }
        public string MetalType { get; set; }
        public double? PctGold { get; set; }
        public double? PctSilver { get; set; }
        public double? PctPlatium { get; set; }
        public short? Karat { get; set; }
        public string MetalColor { get; set; }
        public double? UnitsInStock { get; set; }
        public string Pum { get; set; }
        public string StorageHandling { get; set; }
        public string StorageLocation { get; set; }
        public string ImageLocation { get; set; }
        public DateTime? ImageLastUpdated { get; set; }
        public string JewelryCategory { get; set; }
        public double? Jewelry { get; set; }
        public double? Size { get; set; }
        public double? Length { get; set; }
        public string Style { get; set; }
        public string Thickness { get; set; }
        public string Softness { get; set; }
        public double? InnerDiameter { get; set; }
        public double? OuterDiameter { get; set; }
        public bool? RoutingApply { get; set; }
        public string StoneType { get; set; }
        public float? StoneSize { get; set; }
        public double? StoneWeight { get; set; }
        public string Stonequality { get; set; }
        public string StoneShap { get; set; }
        public string Dshape { get; set; }
        public string Dcolor { get; set; }
        public string Dquality { get; set; }
        public int? SupplierId { get; set; }
        public string Location { get; set; }
        public string Customer { get; set; }
        public string CustomerCode { get; set; }
        public string GroupCode { get; set; }
        public string Class { get; set; }
        public DateTime? LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public DateTime? TransferDate { get; set; }
        public string CpNotes { get; set; }
        public string MainNotes { get; set; }
        public double? QtyOnOrder { get; set; }
        public int? QtyRequired { get; set; }
        public int? Allocated { get; set; }
        public int? AdjustedQty { get; set; }
        public float? MinStockAllowed { get; set; }
        public double? MaxStockAllowed { get; set; }
        public float? MaxWoQtyAllowed { get; set; }
        public int? Fjeu { get; set; }
        public string TrayType { get; set; }
        public string TrayInsert { get; set; }
        public string Qccode { get; set; }
        public float? MarkUp { get; set; }
        public decimal? SettingCost { get; set; }
        public decimal? ProductCost { get; set; }
        public decimal? ManufacturingCost { get; set; }
        public decimal? AssemblyCost { get; set; }
        public string OrderDate { get; set; }
        public int? UnitsSold { get; set; }
        public DateTime? LastSaleDate { get; set; }
        public string TagText1 { get; set; }
        public string TagText2 { get; set; }
        public string TagText3 { get; set; }
        public string TagText4 { get; set; }
        public double? GA { get; set; }
        public bool? Approved1 { get; set; }
        public bool? Approved2 { get; set; }
        public double? Receive { get; set; }
        public double? Scrap { get; set; }
        public double? Lost { get; set; }
        public double? Repairable { get; set; }
        public int? LastYearAdjusted { get; set; }
        public int? LastYearSold { get; set; }
        public double? DateRangeReq { get; set; }
        public double? ActQtyOnOrder { get; set; }
        public float? UnRegLost { get; set; }
        public float? UnRegRepair { get; set; }
        public float? UnRegScrap { get; set; }
        public float? QtyPerTray { get; set; }
        public string DateRangeString { get; set; }
        public double? PrePolish { get; set; }
        public double? FinalPolish { get; set; }
        public bool? TakesFindings { get; set; }
        public bool? TakesCastings { get; set; }
        public bool? TakesRm { get; set; }
        public int? ProductCode { get; set; }
        public string Company { get; set; }
        public string ItemStatus { get; set; }
        public string Cellno { get; set; }
        public int? TiffDept { get; set; }
        public int? TiffClass { get; set; }
        public int? TiffStyle { get; set; }
        public int? TiffColor { get; set; }
        public int? TiffSize { get; set; }
        public string TiffDescription { get; set; }
        public string TiffMfgNo { get; set; }
        public string TiffColorDesc { get; set; }
        public string TiffSizeDesc { get; set; }
        public string TiffStatusCode { get; set; }
        public string TiffCategoryCode { get; set; }
        public string TiffMethodCode { get; set; }
        public string TiffMaterial { get; set; }
        public string Picture { get; set; }
        public string WashGroup { get; set; }
        public bool? PriceActive { get; set; }
        public double? ShippingWtUom { get; set; }
        public string MfgCategory { get; set; }
        public bool SpecialCharge { get; set; }
        public bool? Afy { get; set; }
        public bool? MultiCust { get; set; }
        public decimal? MtcSilverWtgrm { get; set; }
        public decimal? MtcGoldWtgrm { get; set; }
        public short? MtcGoldKt { get; set; }
        public decimal? MtcPtwtgrm { get; set; }
        public decimal? MtcPldwtgrm { get; set; }
        public decimal? MtcStnwtgrm { get; set; }
        public decimal? MtcQcsswt { get; set; }
        public decimal? MtcStoneCost { get; set; }
        public decimal? MfgSilverWtgrm { get; set; }
        public decimal? MfgGoldWtgrm { get; set; }
        public short? MfgGoldKt { get; set; }
        public decimal? MfgPtwtgrm { get; set; }
        public decimal? MfgPldwtgrm { get; set; }
        public decimal? MfgStnwtgrm { get; set; }
        public bool? MtcinvInvalid { get; set; }
        public bool? MtcinvInventory { get; set; }
        public bool? MtcinvTrans { get; set; }
        public bool? InhouseCast { get; set; }
        public decimal? MktpriceSs { get; set; }
        public decimal? MktpriceGold { get; set; }
        public decimal? MktpricePt { get; set; }
        public decimal? MktpricePld { get; set; }
        public string StoneDesc { get; set; }
        public double? StoneQty { get; set; }
        public string StoneWt { get; set; }
        public string Agtacode { get; set; }
        public bool? InspectRange { get; set; }
        public bool? Inspected { get; set; }
        public bool? InspectedBom { get; set; }
        public string BombyUser { get; set; }
        public bool? ActiveStyle { get; set; }
        public string PriceType { get; set; }
        public bool? Hofcasting { get; set; }
        public bool? HofcastingCarrera { get; set; }
        public bool? HofcastingRiva { get; set; }
        public string ProductoldNo { get; set; }
        public string QualityFunctionalRequirements { get; set; }
        public bool? Qaapproved { get; set; }
        public bool? Pdapproved { get; set; }
        public string QfreqType { get; set; }
        public string Gcolor { get; set; }
        public string Pdcategory { get; set; }
        public decimal? RetailPrice { get; set; }
        public decimal? WholeSale { get; set; }
        public byte[] SsmaTimeStamp { get; set; }
    }
}
